<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="1.571" timestamp="2025-07-13T20:21:58.974892+05:30" hostname="fedora"><testcase classname="" name="tests.test_api_endpoints" time="0.000"><error message="collection failure">/home/umbra/.local/lib/python3.13/site-packages/_pytest/python.py:498: in importtestmodule
    mod = import_path(
/home/umbra/.local/lib/python3.13/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/lib64/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
/home/umbra/.local/lib/python3.13/site-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/test_api_endpoints.py:10: in &lt;module&gt;
    from src.api.v1.main import app
E     File "/run/media/umbra/New Volume/projects/Umbra-Educational-Data-Platform/src/api/v1/main.py", line 33
E       app.include_router(learning_paths.router, prefix=\"/learning-paths\", tags=[\"Learning Paths\"])  # Include the learning paths router
E                                                         ^
E   SyntaxError: unexpected character after line continuation character</error></testcase><testcase classname="" name="tests.test_recommendation_model" time="0.000"><error message="collection failure">ImportError while importing test module '/run/media/umbra/New Volume/projects/Umbra-Educational-Data-Platform/tests/test_recommendation_model.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests/test_recommendation_model.py:3: in &lt;module&gt;
    import pandas as pd
E   ModuleNotFoundError: No module named 'pandas'</error></testcase></testsuite></testsuites>